[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    majicDesigns/MD_MAX72XX
    bblanchon/ArduinoJson
    me-no-dev/ESP Async WebServer
    me-no-dev/AsyncTCP