[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^7.4.3
    ESP32Async/ESPAsyncWebServer@^3.8.1
    ESP32Async/AsyncTCP@^3.4.8
    majicdesigns/MD_MAX72XX@^3.5.1